{
 "title": "Traefik AI Gateway Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "model",
    "label": "Model",
    "query": {
     "query": "label_values(gen_ai_client_token_usage_count, gen_ai_request_model)"
    }
   },
   {
    "name": "response_model",
    "label": "Response Model",
    "query": {
     "query": "label_values(gen_ai_client_token_usage_count, gen_ai_response_model)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(gen_ai_client_token_usage_count, app_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (traefik_hub_api_requests_total) by (api_version_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Success",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(api_version_name) (traefik_hub_api_requests_total{code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tokens Saved",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (gen_ai_operation_name) (gen_ai_client_token_usage_sum{cache_status=\"Hit\", gen_ai_request_model=~\"$model\", gen_ai_response_model=~\"$response_model\", app_id=~\"$app\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tokens Spent",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (gen_ai_operation_name) (gen_ai_client_token_usage_sum{cache_status!=\"Hit\", gen_ai_request_model=~\"$model\", gen_ai_response_model=~\"$response_model\", app_id=~\"$app\"})*10000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code) (traefik_hub_api_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Failure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(api_version_name) (traefik_hub_api_requests_total{code!=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code) (traefik_hub_api_requests_total{code!=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token Saved by Model",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (gen_ai_request_model)(gen_ai_client_token_usage_sum{cache_status=\"Hit\", gen_ai_request_model=~\"$model\", gen_ai_response_model=~\"$response_model\", app_id=~\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token Spent by Model",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (gen_ai_request_model)(gen_ai_client_token_usage_sum{cache_status!=\"Hit\", gen_ai_request_model=~\"$model\", gen_ai_response_model=~\"$response_model\", app_id=~\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token Usage by Model",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (gen_ai_request_model)(gen_ai_client_token_usage_sum{gen_ai_request_model=~\"$model\", gen_ai_response_model=~\"$response_model\", app_id=~\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg (rate(traefik_hub_api_requests_total{code=\"200\"}[$__rate_interval])) by (api_version_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(traefik_hub_api_requests_duration_milliseconds_bucket[5m]))by (le, api_version_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requested Models",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(gen_ai_request_model) (gen_ai_client_token_usage_count{gen_ai_token_type=\"input\", gen_ai_request_model=~\"$model\", gen_ai_response_model=~\"$response_model\", app_id=~\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Models",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(gen_ai_request_model) (gen_ai_client_token_usage_count{gen_ai_token_type=\"output\", gen_ai_request_model=~\"$model\", gen_ai_response_model=~\"$response_model\", app_id=~\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token Usage by App",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (app_id) (gen_ai_client_token_usage_count{gen_ai_request_model=~\"$model\", gen_ai_response_model=~\"$response_model\", app_id=~\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,sum(rate(traefik_hub_api_requests_duration_milliseconds_bucket[5m]))by (le, api_version_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration P75",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(traefik_hub_api_requests_duration_milliseconds_bucket[5m]))by (le, api_version_name))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}