
FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY main.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o oci-patcher main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/oci-patcher .

CMD ["./oci-patcher"]
